language: java
matrix:
 include:
 - os: linux
   jdk: openjdk8
   addons:
    apt:
      packages:
      - metacity
   env: DISPLAY=:5009
   script:
   - Xvfb :5009 &
   - metacity --sm-disable &
   - mvn verify -B
   - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
 - os: osx
   osx_image: xcode8.3
   before_install: export JAVA_HOME=$(/usr/libexec/java_home)
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
before_cache:
  - rm -fr $HOME/.m2/repository/nl/esciencecenter/e3dchem/knime/plants
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
install: mvn package -B
